# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui-testwviDQE.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLabel, QLayout,
    QMainWindow, QPushButton, QSizePolicy, QStatusBar,
    QTextEdit, QVBoxLayout, QWidget)

class Ui_home(object):
    def setupUi(self, home):
        if not home.objectName():
            home.setObjectName(u"home")
        home.setEnabled(True)
        home.resize(1109, 750)
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        brush2 = QBrush(QColor(127, 127, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush2)
        brush3 = QBrush(QColor(170, 170, 170, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        brush4 = QBrush(QColor(255, 255, 220, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush5 = QBrush(QColor(0, 0, 0, 128))
        brush5.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        home.setPalette(palette)
        home.setCursor(QCursor(Qt.ArrowCursor))
        home.setAcceptDrops(False)
        home.setAutoFillBackground(True)
        home.setLocale(QLocale(QLocale.Spanish, QLocale.Panama))
        home.setAnimated(True)
        self.centralWidget = QWidget(home)
        self.centralWidget.setObjectName(u"centralWidget")
        self.label = QLabel(self.centralWidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 1071, 41))
        font = QFont()
        font.setFamilies([u"Utopia"])
        font.setPointSize(28)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setAlignment(Qt.AlignCenter)
        self.horizontalLayoutWidget_2 = QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(20, 310, 431, 331))
        self.analisi = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.analisi.setSpacing(6)
        self.analisi.setContentsMargins(11, 11, 11, 11)
        self.analisi.setObjectName(u"analisi")
        self.analisi.setContentsMargins(0, 0, 0, 0)
        self.lexema = QVBoxLayout()
        self.lexema.setSpacing(6)
        self.lexema.setObjectName(u"lexema")
        self.label_2 = QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName(u"label_2")
        font1 = QFont()
        font1.setFamilies([u"Utopia"])
        font1.setPointSize(14)
        font1.setItalic(True)
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignCenter)

        self.lexema.addWidget(self.label_2)

        self.tx_lexico = QTextEdit(self.horizontalLayoutWidget_2)
        self.tx_lexico.setObjectName(u"tx_lexico")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_lexico.sizePolicy().hasHeightForWidth())
        self.tx_lexico.setSizePolicy(sizePolicy)
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush6 = QBrush(QColor(255, 255, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush6)
        brush7 = QBrush(QColor(255, 255, 127, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush7)
        brush8 = QBrush(QColor(255, 255, 63, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush8)
        brush9 = QBrush(QColor(127, 127, 0, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush9)
        brush10 = QBrush(QColor(170, 170, 0, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush10)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush7)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush11 = QBrush(QColor(0, 0, 0, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        brush12 = QBrush(QColor(0, 0, 0, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush10)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush13 = QBrush(QColor(0, 0, 0, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush13)
#endif
        self.tx_lexico.setPalette(palette1)
        font2 = QFont()
        font2.setPointSize(10)
        self.tx_lexico.setFont(font2)

        self.lexema.addWidget(self.tx_lexico)


        self.analisi.addLayout(self.lexema)

        self.verticalLayoutWidget_3 = QWidget(self.centralWidget)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(20, 50, 1071, 251))
        self.fuente = QVBoxLayout(self.verticalLayoutWidget_3)
        self.fuente.setSpacing(7)
        self.fuente.setContentsMargins(11, 11, 11, 11)
        self.fuente.setObjectName(u"fuente")
        self.fuente.setSizeConstraint(QLayout.SetMaximumSize)
        self.fuente.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setEnabled(True)
        font3 = QFont()
        font3.setFamilies([u"Utopia"])
        font3.setPointSize(16)
        font3.setItalic(True)
        self.label_5.setFont(font3)
        self.label_5.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.label_5.setAlignment(Qt.AlignCenter)

        self.fuente.addWidget(self.label_5)

        self.tx_ingreso = QTextEdit(self.verticalLayoutWidget_3)
        self.tx_ingreso.setObjectName(u"tx_ingreso")
        sizePolicy.setHeightForWidth(self.tx_ingreso.sizePolicy().hasHeightForWidth())
        self.tx_ingreso.setSizePolicy(sizePolicy)
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush14 = QBrush(QColor(255, 85, 0, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush14)
        brush15 = QBrush(QColor(255, 170, 127, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush15)
        brush16 = QBrush(QColor(255, 127, 63, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush16)
        brush17 = QBrush(QColor(127, 42, 0, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush17)
        brush18 = QBrush(QColor(170, 56, 0, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush18)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush15)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush19 = QBrush(QColor(0, 0, 0, 128))
        brush19.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush19)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush15)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush16)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush17)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush18)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush15)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        brush20 = QBrush(QColor(0, 0, 0, 128))
        brush20.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush20)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush17)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush15)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush16)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush17)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush18)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush17)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush17)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush21 = QBrush(QColor(0, 0, 0, 128))
        brush21.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush21)
#endif
        self.tx_ingreso.setPalette(palette2)
        font4 = QFont()
        font4.setPointSize(12)
        self.tx_ingreso.setFont(font4)

        self.fuente.addWidget(self.tx_ingreso)

        self.horizontalLayoutWidget = QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(20, 650, 431, 61))
        self.botones = QHBoxLayout(self.horizontalLayoutWidget)
        self.botones.setSpacing(100)
        self.botones.setContentsMargins(11, 11, 11, 11)
        self.botones.setObjectName(u"botones")
        self.botones.setContentsMargins(50, 0, 50, 5)
        self.bt_lexico = QPushButton(self.horizontalLayoutWidget)
        self.bt_lexico.setObjectName(u"bt_lexico")
        sizePolicy.setHeightForWidth(self.bt_lexico.sizePolicy().hasHeightForWidth())
        self.bt_lexico.setSizePolicy(sizePolicy)
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        brush22 = QBrush(QColor(0, 255, 0, 255))
        brush22.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush22)
        brush23 = QBrush(QColor(127, 255, 127, 255))
        brush23.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush23)
        brush24 = QBrush(QColor(63, 255, 63, 255))
        brush24.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush24)
        brush25 = QBrush(QColor(0, 127, 0, 255))
        brush25.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush25)
        brush26 = QBrush(QColor(0, 170, 0, 255))
        brush26.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush26)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush22)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush23)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush27 = QBrush(QColor(0, 0, 0, 128))
        brush27.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush27)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush23)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush24)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush25)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush26)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush22)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush23)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        brush28 = QBrush(QColor(0, 0, 0, 128))
        brush28.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush28)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush25)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush23)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush24)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush25)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush26)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush25)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush25)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush22)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush22)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush22)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush29 = QBrush(QColor(0, 0, 0, 128))
        brush29.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush29)
#endif
        self.bt_lexico.setPalette(palette3)
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(True)
        self.bt_lexico.setFont(font5)
        self.bt_lexico.setCursor(QCursor(Qt.PointingHandCursor))
        self.bt_lexico.setAutoFillBackground(False)

        self.botones.addWidget(self.bt_lexico)

        self.horizontalLayoutWidget_3 = QWidget(self.centralWidget)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(10, 50, 221, 31))
        self.archivo = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.archivo.setSpacing(6)
        self.archivo.setContentsMargins(11, 11, 11, 11)
        self.archivo.setObjectName(u"archivo")
        self.archivo.setContentsMargins(10, 0, 10, 0)
        self.bt_archivo = QPushButton(self.horizontalLayoutWidget_3)
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush14)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush15)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush16)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush17)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush18)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush15)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush30 = QBrush(QColor(0, 0, 0, 128))
        brush30.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush30)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush14)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush15)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush16)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush17)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush18)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush14)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush15)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        brush31 = QBrush(QColor(0, 0, 0, 128))
        brush31.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush31)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush17)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush15)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush16)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush17)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush18)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush17)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush17)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush32 = QBrush(QColor(0, 0, 0, 128))
        brush32.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush32)
#endif
        self.bt_archivo.setPalette(palette4)
        font6 = QFont()
        font6.setBold(True)
        font6.setUnderline(False)
        font6.setStrikeOut(False)
        self.bt_archivo.setFont(font6)
        self.bt_archivo.setObjectName(u"bt_archivo")
        self.archivo.addWidget(self.bt_archivo)

        self.bt_limpiar = QPushButton(self.horizontalLayoutWidget_3)
        self.bt_limpiar.setObjectName(u"bt_limpiar")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.bt_limpiar.sizePolicy().hasHeightForWidth())
        self.bt_limpiar.setSizePolicy(sizePolicy1)
        font7 = QFont()
        font7.setBold(True)
        self.bt_limpiar.setFont(font7)
        self.bt_limpiar.setFocusPolicy(Qt.StrongFocus)
        self.bt_limpiar.setIconSize(QSize(16, 16))

        self.archivo.addWidget(self.bt_limpiar)

        self.layoutWidget = QWidget(self.centralWidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(460, 310, 631, 331))
        self.gramatica = QVBoxLayout(self.layoutWidget)
        self.gramatica.setSpacing(6)
        self.gramatica.setContentsMargins(11, 11, 11, 11)
        self.gramatica.setObjectName(u"gramatica")
        self.gramatica.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignCenter)

        self.gramatica.addWidget(self.label_3)

        self.tx_sintactico = QTextEdit(self.layoutWidget)
        self.tx_sintactico.setObjectName(u"tx_sintactico")
        sizePolicy.setHeightForWidth(self.tx_sintactico.sizePolicy().hasHeightForWidth())
        self.tx_sintactico.setSizePolicy(sizePolicy)
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush22)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush23)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush24)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush25)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush26)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush22)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush23)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush33 = QBrush(QColor(0, 0, 0, 128))
        brush33.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush33)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush22)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush23)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush24)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush25)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush26)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush22)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush23)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        brush34 = QBrush(QColor(0, 0, 0, 128))
        brush34.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush34)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush25)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush22)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush23)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush24)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush25)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush26)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush25)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush25)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush22)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush22)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush22)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush35 = QBrush(QColor(0, 0, 0, 128))
        brush35.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush35)
#endif
        self.tx_sintactico.setPalette(palette5)
        self.tx_sintactico.setFont(font2)

        self.gramatica.addWidget(self.tx_sintactico)

        self.horizontalLayoutWidget_4 = QWidget(self.centralWidget)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(460, 650, 631, 61))
        self.botones_2 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.botones_2.setSpacing(100)
        self.botones_2.setContentsMargins(11, 11, 11, 11)
        self.botones_2.setObjectName(u"botones_2")
        self.botones_2.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.botones_2.setContentsMargins(50, 0, 50, 5)
        self.bt_sintactico = QPushButton(self.horizontalLayoutWidget_4)
        self.bt_sintactico.setObjectName(u"bt_sintactico")
        sizePolicy.setHeightForWidth(self.bt_sintactico.sizePolicy().hasHeightForWidth())
        self.bt_sintactico.setSizePolicy(sizePolicy)
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush36 = QBrush(QColor(255, 170, 0, 255))
        brush36.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush36)
        brush37 = QBrush(QColor(255, 213, 127, 255))
        brush37.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush37)
        brush38 = QBrush(QColor(255, 191, 63, 255))
        brush38.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush38)
        brush39 = QBrush(QColor(127, 85, 0, 255))
        brush39.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush39)
        brush40 = QBrush(QColor(170, 113, 0, 255))
        brush40.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush40)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush36)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush)
        brush41 = QBrush(QColor(255, 212, 127, 255))
        brush41.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush41)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush4)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush42 = QBrush(QColor(0, 0, 0, 128))
        brush42.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush42)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush36)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush37)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush38)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush39)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush40)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush36)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush41)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush4)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        brush43 = QBrush(QColor(0, 0, 0, 128))
        brush43.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush43)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush39)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush36)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush37)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush38)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush39)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush40)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush39)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush39)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush36)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush36)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush36)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush4)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush44 = QBrush(QColor(0, 0, 0, 128))
        brush44.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush44)
#endif
        self.bt_sintactico.setPalette(palette6)
        self.bt_sintactico.setFont(font5)
        self.bt_sintactico.setCursor(QCursor(Qt.PointingHandCursor))
        self.bt_sintactico.setLayoutDirection(Qt.LeftToRight)

        self.botones_2.addWidget(self.bt_sintactico)

        home.setCentralWidget(self.centralWidget)
        self.estado = QStatusBar(home)
        self.estado.setObjectName(u"estado")
        font8 = QFont()
        font8.setFamilies([u"NanumGothicExtraBold"])
        font8.setPointSize(14)
        font8.setBold(True)
        self.estado.setFont(font8)
        home.setStatusBar(self.estado)

        self.retranslateUi(home)
        QMetaObject.connectSlotsByName(home)
        home.setTabOrder(self.bt_lexico, self.bt_sintactico)
        home.setTabOrder(self.bt_sintactico, self.tx_lexico)
        home.setTabOrder(self.tx_lexico, self.tx_sintactico)
        home.setTabOrder(self.tx_sintactico, self.bt_archivo)
        home.setTabOrder(self.bt_archivo, self.bt_limpiar)
        home.setTabOrder(self.bt_limpiar, self.tx_ingreso)
    # setupUi

    def retranslateUi(self, home):
        home.setWindowTitle(QCoreApplication.translate("home", u"Analizador lexico y sintactico", None))
        self.label.setText(QCoreApplication.translate("home", u"Analizador - Lexico - Sintactico", None))
        self.label_2.setText(QCoreApplication.translate("home", u"Analisis Lexico", None))
        self.tx_lexico.setHtml(QCoreApplication.translate("home", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Sans Serif'; font-size:9pt;\"><br /></p></body></html>", None))
        self.tx_lexico.setPlaceholderText(QCoreApplication.translate("home", u"Analisis de lexemas", None))
        self.label_5.setText(QCoreApplication.translate("home", u"Codigo Fuente", None))
        self.tx_ingreso.setHtml(QCoreApplication.translate("home", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Sans Serif'; font-size:9pt;\"><br /></p></body></html>", None))
        self.tx_ingreso.setPlaceholderText(QCoreApplication.translate("home", u"Ingrese el texto a analizar o suba un archivo", None))
        self.bt_lexico.setText(QCoreApplication.translate("home", u"Analizar Lexico", None))
        self.bt_archivo.setText(QCoreApplication.translate("home", u"Subir Archivo", None))
        self.bt_limpiar.setText(QCoreApplication.translate("home", u"Borrar", None))
        self.label_3.setText(QCoreApplication.translate("home", u"Analisis Sintactico", None))
        self.tx_sintactico.setPlaceholderText(QCoreApplication.translate("home", u"Analisis de gramatica libre de contexto", None))
        self.bt_sintactico.setText(QCoreApplication.translate("home", u"Analisis Sintactico", None))
    # retranslateUi

